pool:
  vmImage: 'ubuntu-16.04'

variables: # pipeline-level
  BUILD_ENV: 'PROD'

steps:
- script: docker run -d --name=rm-test-mongo mongo
  displayName: 'installing latest mongodb docker image'

- script: sudo npm install -g @angular/cli
  displayName: 'installing angular7 CLI'

- script: |
    sudo mkdir -p $(Build.SourcesDirectory)/appRoot
    cd $(Build.SourcesDirectory)/appRoot
    sudo ng new demo --defaults
  displayName: 'create demo angular project'

- script: |
    ls $(Build.SourcesDirectory)
    sudo cp -r $(Build.SourcesDirectory)/demo/. $(Build.SourcesDirectory)/appRoot/demo
  displayName: 'laying generated demo source over angular project'

- script: |
    cd $(Build.SourcesDirectory)/appRoot/demo
    sudo npm install --${BUILD_ENV}
    sudo npm audit fix
  displayName: 'installing app depenedencies'

- script: |
    cd $(Build.SourcesDirectory)/appRoot/demo
    sudo npm run setup
  displayName: 'running mongoose/mongodb setup'

- script: |
    cd $(Build.SourcesDirectory)/appRoot/demo
    sudo ng build
    
  displayName: 'build the entire application'
   